---
- name: sendmail uninstall
  package:
    name: sendmail
    state: absent

- name: postfix install
  package:
    name: postfix
    state: present

- name: postfix configuration generation
  template:
    src: main.cf.j2
    dest: "{{ postfix_config_file }}"
    mode: 0644
  notify: postfix reload

- name: postfix enable
  service:
    name: postfix
    state: "{{ postfix_service_state }}"
    enabled: "{{ postfix_service_enabled }}"